### ISSUE TITLE
Mettre les horaires en back-office

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/lacriee-site#14]
Ouvert de 13h à 19h
du jeudi au dimanche,
de 18h30 à 20h le mercredi
<img width="305" alt="Capture d’écran 2024-01-29 à 17 20 50" src="https://github.com/noesya/lacriee-site/assets/2088968/b7f5d93f-7911-4f09-a06d-913951ca05a0">

**Comment by alexisben** [comment]
Ça irait dans data/website.yml ? Dites dès que c'est géré on fera le switch et on intégrera en pied de page dans le thème par défaut

**Comment by arnaudlevy** [comment]
je sais pas où ça doit aller.
C'est quoi là ? En dur ?

Je pense qu'il faut plutôt utiliser le résumé de la home. ok ?
