### ISSUE TITLE
Rétrocompatibilité : affichage des images parfois trop petites

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/lacriee-site#28]
[https://lacriee-site.web.deuxfleurs.fr/fr/ressources/les-correspondants/charbel-joseph-h-boutros-the-sun-is-my-only-ally-le-soleil-est-mon-seul-allie-les-correspondants/](https://lacriee-site.web.deuxfleurs.fr/fr/ressources/les-correspondants/charbel-joseph-h-boutros-the-sun-is-my-only-ally-le-soleil-est-mon-seul-allie-les-correspondants/)

Windows 10 Professionnel | Firefox

**Comment by Olivia206** [comment]
Je ne trouve pas où se présente le pb : 

<img width="601" alt="Capture d’écran 2024-05-23 à 12 44 57" src="https://github.com/osunyorg/lacriee-site/assets/91660674/10e0c1a4-049c-4ad2-b444-4b1d7aa97630">

**Comment by pabois** [comment]
je pense que le problème évoqué est lié au fait qu'à certains endroits ils ont envoyé des images vraiment trop petites, qui du coup sont agrandies.
J'ai évoqué ce point avec eux au tel la semaine dernière, il est possible qu'ils aient déjà amélioré en envoyant des images plus grande aux endroits concernés

**Comment by Olivia206** [comment]
Ah d'accord, merci !
