### ISSUE TITLE
Footer : ajout de logos

### ISSUE THREAD

**Issue by Olivia206** [osunyorg/lacriee-site#33]
![simulation-footer-site-internet-avec-partenaires-avec-lignes-de-pose](https://github.com/osunyorg/lacriee-site/assets/91660674/635a0a5e-b4d3-4150-bd11-d4d45bf083b9)

**Comment by pabois** [comment]
![maquette-footer](https://github.com/osunyorg/lacriee-site/assets/2145137/fe51c60b-837e-4902-aecb-26d1c48aacbb)
