### ISSUE TITLE
Pbs en mobile

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/lacriee-site#35]
## Home

<img width="467" alt="Capture d’écran 2024-06-10 à 15 14 19" src="https://github.com/osunyorg/lacriee-site/assets/2088968/ac0c2b3b-06e4-4352-bcf1-6f9d9b274b82">

- [x] Pb de rythme à cause du glyphe
- [x] Glyphe sur dimanche

<img width="486" alt="Capture d’écran 2024-06-10 à 15 17 03" src="https://github.com/osunyorg/lacriee-site/assets/2088968/a0b6163e-262a-441d-984d-ddd78c854a74">

- [x] Dates incohérentes (remonter la cohérence dans le thème je pense)

<img width="454" alt="Capture d’écran 2024-06-10 à 15 17 49" src="https://github.com/osunyorg/lacriee-site/assets/2088968/f77e89e5-558f-498c-bff5-08e81854f7f4">

- [x] Il faudrait masque le <br> entre "Rennes." et "Elle est" pour faire un seul paragraphe
- [x] Dans la recherche, il faudrait un insécable à "un événement", et ce serait mieux d'aligner à gauche sur "Rechercher"

## Programmation
https://www.la-criee.org/fr/programmation/cycle-thematique-festina-lente-hate-toi-lentement/

<img width="464" alt="Capture d’écran 2024-06-10 à 15 21 12" src="https://github.com/osunyorg/lacriee-site/assets/2088968/d32c4a44-41fd-42e0-9653-8094b70b4c70">

- [x] Mettre le petit glyphe étoile à la place du | ?

## Personne
https://www.la-criee.org/fr/auteurices-du-site/lea-muller/

<img width="439" alt="Capture d’écran 2024-06-10 à 15 23 28" src="https://github.com/osunyorg/lacriee-site/assets/2088968/492e9c04-53c8-460c-986f-c9ff2bde1eeb">

C'est volontaire le placement image ?

**Comment by Olivia206** [comment]
Effectivement pour les dates c'est côté thème : [#469](https://github.com/osunyorg/theme/issues/469)

**Comment by Olivia206** [comment]
Je viens de push la dernière modif (les dates), je ferme !
