### ISSUE TITLE
Harmonisation des pages parents

### ISSUE THREAD

**Issue by MagaliAngles** [osunyorg/lacriee-site#40]
Sur les pages suivantes, la mise en en avant des pages enfantes n'est pas harmonisée car il manque soit des résumés ou des photos dans les pages enfantes. 
Si les contenus manquants ne sont pas encore créés, est-ce qu'il y a moyen de pouvoir choisir d'afficher que le titre de la page enfant, ou titre + résumé ou titre + résume + photo quand tous les contenus sont créés ?
https://www.la-criee.org/fr/programmation/
https://www.la-criee.org/fr/centre-dart/
https://www.la-criee.org/en/all-the-programme/
https://www.la-criee.org/en/art-center/

**Comment by Olivia206** [comment]
Hello @MagaliAngles 

C'est du souci de contenu, actuellement il faut simplement soigner ces pages
On a des interrogations ceci dit au sujet des options sur les pages, mais ce n'est pas pour tout de suite !
